INSERT INTO stadiums(name, capacity, city, country) VALUES('Monumental de la U',80903,'Lima','Peru');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Maracanã',78838,'Rio de Janeiro','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Mané Garrincha',72788,'Brasília','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Morumbi',72039,'São Paulo','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Monumental de Núñez',70074,'Buenos Aires','Argentina');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Mineirão',61846,'Belo Horizonte','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Arena do Grêmio',60540,'Porto Alegre','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Centenario',60235,'Monetevidéu','Uruguay');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Estadio Nacional del Peru',60000,'Lima','Peru');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Arruda',60044,'Recife','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Estadio Monumental Isidro Romero Carbo',57267,'Guayaquil','Ecuador');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Estadio Mario Alberto Kempes',57000,'Córdoba','Argentina');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Estadio La Bombonera',54000,'Buenos Aires','Argentina');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Municipal João Avelange',53350,'Uberlândia','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Ciudad de La Plata',53000,'Buenos Aires','Argentina');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Castelão',52552,'Fortaleza','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Deportivo Cali',52000,'Cali','Colombia');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Monumental de Maturín',51796,'Maturín','Venezuela');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Presidente Juan Domingo Perón',51389,'Buenos Aires','Argentina');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Beira-Rio',50842,'Porto Alegre','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Libertadores da America',49592,'Buenos Aires','Argentina');
INSERT INTO stadiums(name, capacity, city, country) VALUES('José Amalfitani',49540,'Buenos Aires','Argentina');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Néo Química Arena',49205,'São Paulo','Brasil');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Nacional de Chile',48665,'Santiago','Chile');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Metropolitano Lara',47913,'Cabudare','Venezuela');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Monumental de Chile',47347,'Santiago','Chile');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Ciudad de Lanús',47027,'Lanús','Argentina');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Metropolitano de Barranquilla',46692,'Barranquilla','Colombia');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Olímpico Pascual Guerrero',46400,'Cali','Colombia');
INSERT INTO stadiums(name, capacity, city, country) VALUES('General Pablo Rojas',45000,'Assunção','Paraguay');
INSERT INTO stadiums(name, capacity, city, country) VALUES('Atanasio Girardot',44739,'Medellín','Colombia');